### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by fkreiner** [sschaeffner/fabXdashboard#1]
Implement environment variables (to be used during build process) for backend URL and such things

**Comment by sschaeffner** [comment]
Here is an overview of the options: https://www.mokkapps.de/blog/how-to-build-an-angular-app-once-and-deploy-it-to-multiple-environments/
* Evaluating browser URL: not an option as backend is hosted at completely different URL (and we do not have an api gateway or similar in front of both backend and frontend)
* Endpoint with backend URLs: not an option for instances run by other organisations
* mounting configuration file from environment: possible but no improvement over current configuration file
* overriding environment configuration file automatically: overly complicated

We can reopen this if an option that makes sense for instances run by different organisations and is not a configuration file (as currently) comes around.
